language: swift
osx_image: xcode8.3
os: osx

branches:
 only:
 - master
 - dev

script:
- xcodebuild -project WeatherService.xcodeproj -scheme WeatherService -destination 'platform=iOS Simulator,name=iPhoneSE,OS=10.3' clean build test | xcpretty
